---
swagger: "2.0"
info:
  x-ibm-name: "authenticationapi"
  title: "AuthenticationAPI"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/authenticationapi"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  Basic:
    type: "basic"
    description: ""
    x-ibm-authentication-url:
      url: "https://httpbin.org/basic-auth/Abhishek/Awasthi"
security:
- Basic: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - activity-log:
        title: "activity-log"
        content: "payload"
        error-content: "payload"
        version: "1.0.0"
  phase: "realized"
paths:
  /identity:
    get:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
