---
swagger: "2.0"
info:
  x-ibm-name: "dummyapi"
  title: "dummyAPI"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/dummyapi"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  Oauth:
    type: "oauth2"
    description: ""
    flow: "application"
    scopes:
      accounts: ""
      payments: ""
    tokenUrl: "https://api.us-south.apiconnect.appdomain.cloud/xawdcvgmailcom-dev/sb/dummyoauth/oauth2/token"
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
- Oauth:
  - "accounts"
  - "payments"
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        title: "gatewayscript"
        version: "1.0.0"
        source: "var response = {\n    \"Authenticated\" : true,\n    \"name\" : 'Abhishek'\n\
          }\n\napim.setvariable('message.body',response) \n"
  phase: "realized"
paths:
  /accounts:
    get:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
